# services:
#   database:
#     image: postgres
#     container_name: database_atividade
#     restart: always
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_USER=docker
#       - POSTGRES_PASSWORD=atividade
#       - POSTGRES_DB=atividade
#     volumes:
#       - pgdata:/data/postgres

services:
  database:
    image: postgres
    container_name: database_post
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=post
      - POSTGRES_DB=post
    volumes:
      - pgdata:/data/postgres

  # app:
  #   build: .
  #   container_name: post
  #   restart: always
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on:
  #     - database
  
volumes:
  pgdata:
    driver: local
